# Short bio or description (displayed in the header)
description: School of Computer Science, Wuhan University.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/weitang.jpg

theme: jekyll-theme-cayman
